import type {
  Evaluation,
  Quotation,
  Recommendation,
  VendorComparison,
} from "@/lib/types";

export const dashboardStats = [
  { label: "Total evaluations", value: "24", change: "+3 this month" },
  { label: "Active evaluations", value: "6", change: "2 need review" },
  { label: "Completed", value: "18", change: "75% completion" },
  { label: "Vendors analysed", value: "57", change: "+8 this month" },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: "EV-2026-024",
    title: "Computer Lab Laptop Procurement",
    category: "IT Equipment",
    quantity: 25,
    budget: "4000000",
    currency: "PKR",
    requiredDeliveryDays: 14,
    status: "RECOMMENDATION_READY",
    quotationsCount: 3,
    recommendedVendor: "TechCore Solutions",
    createdAt: "2026-08-07T10:30:00Z",
    updatedAt: "2026-08-09T08:15:00Z",
    requirements: [],
  },
  {
    id: "EV-2026-023",
    title: "Regional Office Network Upgrade",
    category: "Network Infrastructure",
    quantity: 12,
    budget: "2850000",
    currency: "PKR",
    requiredDeliveryDays: 21,
    status: "REVIEW_REQUIRED",
    quotationsCount: 3,
    recommendedVendor: null,
    createdAt: "2026-08-05T12:00:00Z",
    updatedAt: "2026-08-08T16:22:00Z",
    requirements: [],
  },
  {
    id: "EV-2026-022",
    title: "Finance Team Workstations",
    category: "IT Equipment",
    quantity: 18,
    budget: "3600000",
    currency: "PKR",
    requiredDeliveryDays: 14,
    status: "SCORED",
    quotationsCount: 3,
    recommendedVendor: "Nexa Systems",
    createdAt: "2026-08-02T09:10:00Z",
    updatedAt: "2026-08-06T11:40:00Z",
    requirements: [],
  },
  {
    id: "EV-2026-021",
    title: "Warehouse Barcode Scanners",
    category: "Operations Equipment",
    quantity: 40,
    budget: "1900000",
    currency: "PKR",
    requiredDeliveryDays: 10,
    status: "QUOTATIONS_UPLOADED",
    quotationsCount: 2,
    recommendedVendor: null,
    createdAt: "2026-07-29T14:20:00Z",
    updatedAt: "2026-08-04T13:05:00Z",
    requirements: [],
  },
  {
    id: "EV-2026-020",
    title: "Customer Support Headsets",
    category: "Office Technology",
    quantity: 60,
    budget: "750000",
    currency: "PKR",
    requiredDeliveryDays: 7,
    status: "DRAFT",
    quotationsCount: 0,
    recommendedVendor: null,
    createdAt: "2026-07-26T08:30:00Z",
    updatedAt: "2026-07-26T08:30:00Z",
    requirements: [],
  },
];

export const mockQuotations: Quotation[] = [
  {
    id: "quote-techcore",
    evaluationId: "EV-2026-024",
    vendorName: "TechCore Solutions",
    fileName: "TechCore_Latitude_Quotation.pdf",
    fileSize: 2457600,
    processingStatus: "READY",
    reviewed: false,
    extraction: {
      vendorName: "TechCore Solutions",
      productName: "Dell Latitude Business Laptop",
      productModel: "Dell Latitude 5550",
      quantity: 25,
      unitPrice: "145000.00",
      currency: "PKR",
      subtotal: "3625000.00",
      taxAmount: "0.00",
      totalPrice: "3625000.00",
      deliveryDays: 10,
      warrantyMonths: 36,
      paymentTerms: "50% advance, 50% on delivery",
      supportDetails: "Three-year onsite support included",
      quotationValidityDays: 30,
      sourcePages: { vendorName: 1, productModel: 2, totalPrice: 3 },
      reviewed: false,
    },
  },
  {
    id: "quote-nexa",
    evaluationId: "EV-2026-024",
    vendorName: "Nexa Systems",
    fileName: "Nexa_Systems_Proposal.pdf",
    fileSize: 1835008,
    processingStatus: "READY",
    reviewed: false,
    extraction: {
      vendorName: "Nexa Systems",
      productName: "HP ProBook Laptop",
      productModel: "HP ProBook 450 G10",
      quantity: 25,
      unitPrice: "139000.00",
      currency: "PKR",
      subtotal: "3475000.00",
      taxAmount: "0.00",
      totalPrice: "3475000.00",
      deliveryDays: 18,
      warrantyMonths: 24,
      paymentTerms: "Full payment prior to dispatch",
      supportDetails: "Remote support during business hours",
      quotationValidityDays: 14,
      sourcePages: { vendorName: 1, productModel: 1, totalPrice: 2 },
      reviewed: false,
    },
  },
  {
    id: "quote-orbit",
    evaluationId: "EV-2026-024",
    vendorName: "Orbit Technologies",
    fileName: "Orbit_Laptop_Bid.pdf",
    fileSize: 3211264,
    processingStatus: "READY",
    reviewed: false,
    extraction: {
      vendorName: "Orbit Technologies",
      productName: "Lenovo ThinkPad Laptop",
      productModel: "ThinkPad E16 Gen 2",
      quantity: 25,
      unitPrice: "151800.00",
      currency: "PKR",
      subtotal: "3795000.00",
      taxAmount: null,
      totalPrice: "3795000.00",
      deliveryDays: 12,
      warrantyMonths: 12,
      paymentTerms: "30% advance, balance on delivery",
      supportDetails: null,
      quotationValidityDays: 21,
      extractionNotes: [
        "Tax treatment is not clearly stated.",
        "Support coverage was not found in the quotation.",
      ],
      sourcePages: { vendorName: 1, productModel: 2, totalPrice: 2 },
      reviewed: false,
    },
  },
];

export const mockComparison: VendorComparison[] = [
  {
    id: "quote-techcore",
    vendorName: "TechCore Solutions",
    totalPrice: 3625000,
    currency: "PKR",
    compliancePercentage: 100,
    deliveryDays: 10,
    warrantyMonths: 36,
    priceScore: 95.9,
    technicalScore: 100,
    deliveryScore: 100,
    warrantyScore: 100,
    paymentScore: 80,
    supportScore: 90,
    overallScore: 95.6,
    status: "COMPLIANT",
    rank: 1,
    isRecommended: true,
  },
  {
    id: "quote-nexa",
    vendorName: "Nexa Systems",
    totalPrice: 3475000,
    currency: "PKR",
    compliancePercentage: 86,
    deliveryDays: 18,
    warrantyMonths: 24,
    priceScore: 100,
    technicalScore: 86,
    deliveryScore: 54,
    warrantyScore: 80,
    paymentScore: 45,
    supportScore: 65,
    overallScore: 82.3,
    status: "PARTIALLY_COMPLIANT",
    rank: 2,
    failedRequirement: "Delivery within 14 days",
  },
  {
    id: "quote-orbit",
    vendorName: "Orbit Technologies",
    totalPrice: 3795000,
    currency: "PKR",
    compliancePercentage: 71,
    deliveryDays: 12,
    warrantyMonths: 12,
    priceScore: 91.6,
    technicalScore: 71,
    deliveryScore: 88,
    warrantyScore: 40,
    paymentScore: 70,
    supportScore: 20,
    overallScore: 74.9,
    status: "NON_COMPLIANT",
    rank: null,
    failedRequirement: "Minimum 24-month warranty",
  },
];

export const mockRecommendation: Recommendation = {
  recommendedVendor: "TechCore Solutions",
  summary:
    "TechCore Solutions offers the strongest overall value and is the only vendor to satisfy every mandatory requirement. Its slightly higher price is offset by faster delivery, a longer warranty, and stronger onsite support.",
  strengths: [
    "Meets all seven mandatory procurement requirements",
    "Delivery is four days inside the required timeline",
    "36-month onsite warranty offers the best risk coverage",
  ],
  risks: [
    "Requires a 50% advance payment",
    "Total price is PKR 150,000 above the cheapest bid",
  ],
  missingInformation: [
    "Confirm whether quoted prices include all withholding taxes",
  ],
  cheaperVendorReason:
    "Nexa Systems submitted the lowest price, but its 18-day delivery estimate fails the mandatory 14-day delivery requirement and its payment terms create higher cash-flow exposure.",
  generatedAt: "2026-08-09T08:15:00Z",
};
